spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mylog_db}
    username: ${SPRING_DATASOURCE_USERNAME:mylog_user}
    password: ${SPRING_DATASOURCE_PASSWORD:secure_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:rabbitmq_user}
    password: ${SPRING_RABBITMQ_PASSWORD:rabbitmq_password}
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    mylog_backend.mylog: DEBUG

# 환경별 프로필 설정
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  info:
    title: MyLog Swagger UI
    description: API docs for MyLog project
    version: 1.0.0

jwt:
  secret-key : ${JWT_SECRET_KEY}