services:

  mylog-application:
    image: "${DOCKER_HUB_USERNAME}/mylog:v.0.0.1" # 프로젝트 버전이 바뀔때마다 변경
#    build: . # 배포시 이미 빌드된 이미지를 가져오므로 삭제
    container_name: mylog-springboot
    ports:
      - "18080:8080" # 서버 외부 포트를 18080으로 설정
    env_file:
      - ./.env
    depends_on:
      mylog-postgres:
        condition: service_healthy # postgres가 켜질때까지 기다림
      mylog-rabbitmq:
        condition: service_healthy # rabbitmq를 기다림
      mylog-redis:
        condition: service_healthy # Redis가 'healthy' 상태가 될 때까지 기다림
    environment: # 환경변수 설정
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mylog-postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_HOST=mylog-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - SPRING_REDIS_HOST=mylog-redis
      - SPRING_REDIS_PORT=6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    networks:
      - mylog_app-network


  mylog-postgres:
    image: "postgres:17"
    container_name: mylog-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # PostgreSQL이 띄워질때까지 확인
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ] # 컨테이너가 실행되는지 확인하는 명령어
      interval: 10s # 상태를 확인하는 주기
      timeout: 5s # 확인했을때 5초간 응답이 없으면 실패했다고 판단
      retries: 5 # 최대 시도 횟수
    networks:
      - mylog_app-network



  mylog-rabbitmq:
    container_name: mylog-rabbitmq
    image: "rabbitmq:4-management"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - mylog_app-network



  mylog-redis:
    container_name: mylog-redis
    image: "redis:7" # redis 버전 명시
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - mylog_app-network



  # prometheus, grafana 설정시 추가
  mylog-prometheus:
    image: "prom/prometheus:v2.53.4"
    container_name: mylog-prometheus
    ports:
      - "19090:9090" # http://localhost:19090/
    volumes:
      - ./src/main/java/mylog_backend/mylog/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: # prometheus.yml의 설정대로 실행
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mylog_app-network


  mylog-grafana:
    image: "grafana/grafana:12.0.1"
    container_name: mylog-grafana
    volumes: # src/main 내 프로젝트 폴더에 위치
      - ./src/main/java/mylog_backend/mylog/grafana:/etc/grafana/provisioning
      - ./src/main/java/mylog_backend/mylog/grafana/data:/var/lib/grafana
    ports:
      - "13000:3000"
    networks:
      - mylog_app-network




# 다른 컨테이너끼리 이름으로 통신 가능
networks:
  mylog_app-network:
    name: mylog_app-network
    driver: bridge

volumes:
  postgres_data:
